---
apiVersion: v1
kind: Service
metadata:
  name: spcservice
  labels:
    app: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  type: NodePort
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spcdeployment
  labels:
    app: spring-petclinic
  namespace: staging
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      name: spring-petclinic
      labels:
        app: spring-petclinic
    spec:
      containers:
        - image: sanjaygreddy/spring-petclinic
          name: spring-petclinic
          ports:
            - containerPort: 8080
          imagePullPolicy: Always